export const LANGUAGES = [
  { name: 'Bash', value: 'bash' },
  { name: 'C#', value: 'csharp' },
  { name: 'C', value: 'c' },
  { name: 'C++', value: 'cpp' },
  { name: 'CMake', value: 'cmake' },
  { name: 'CSS', value: 'css' },
  { name: 'DOS', value: 'dos' },
  { name: 'Dart', value: 'dart' },
  { name: 'Django', value: 'django' },
  { name: 'Dockerfile', value: 'dockerfile' },
  { name: 'Excel', value: 'excel' },
  { name: 'Go', value: 'go' },
  { name: 'HTML, XML', value: 'xml' },
  { name: 'HTTP', value: 'http' },
  { name: 'Handlebars', value: 'handlebars' },
  { name: 'Haskell', value: 'haskell' },
  { name: 'JSON', value: 'json' },
  { name: 'Java', value: 'java' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'LaTeX', value: 'tex' },
  { name: 'Less', value: 'less' },
  { name: 'Makefile', value: 'makefile' },
  { name: 'Markdown', value: 'markdown' },
  { name: 'Nginx', value: 'nginx' },
  { name: 'Objective C', value: 'objectivec' },
  { name: 'PHP', value: 'php' },
  { name: 'Plaintext', value: 'plaintext' },
  { name: 'PostgreSQL & PL/pgSQL', value: 'pgsql' },
  { name: 'PowerShell', value: 'powershell' },
  { name: 'Python', value: 'python' },
  { name: 'Python profiler results', value: 'profile' },
  { name: 'Python REPL', value: 'python-repl' },
  { name: 'QML', value: 'qml' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Rust', value: 'rust' },
  { name: 'SCSS', value: 'scss' },
  { name: 'SQL', value: 'sql' },
  { name: 'Shell', value: 'shell' },
  { name: 'Stylus', value: 'stylus' },
  { name: 'Swift', value: 'swift' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'VB.Net', value: 'vbnet' },
  { name: 'VBScript', value: 'vbscript' },
  { name: 'YAML', value: 'yml' },
]
