/* eslint-disable */
/**
 * ---------------------------------------------------------
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
 * ---------------------------------------------------------
 */
import { z } from "zod";

export enum ErrorCode {
  IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR = "IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR",
  IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR = "IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR",
  INVALID_FRIENDSHIP_ACTION_ERROR = "INVALID_FRIENDSHIP_ACTION_ERROR",
  MISSING_PASSWORD_ERROR = "MISSING_PASSWORD_ERROR",
  NOT_VERIFIED_ACCOUNT_ERROR = "NOT_VERIFIED_ACCOUNT_ERROR",
  PASSWORD_RESET_TOKEN_EXPIRED_ERROR = "PASSWORD_RESET_TOKEN_EXPIRED_ERROR",
  PASSWORD_RESET_TOKEN_INVALID_ERROR = "PASSWORD_RESET_TOKEN_INVALID_ERROR",
  PASSWORD_VALIDATION_ERROR = "PASSWORD_VALIDATION_ERROR",
  VERIFICATION_TOKEN_EXPIRED_ERROR = "VERIFICATION_TOKEN_EXPIRED_ERROR",
  VERIFICATION_TOKEN_INVALID_ERROR = "VERIFICATION_TOKEN_INVALID_ERROR",
  EMAIL_ADDRESS_CONFLICT_ERROR = "EMAIL_ADDRESS_CONFLICT_ERROR",
  INVALID_CREDENTIALS_ERROR = "INVALID_CREDENTIALS_ERROR",
  NATIVE_AUTH_STRATEGY_ERROR = "NATIVE_AUTH_STRATEGY_ERROR",
}

export const errorCodeEnum = z.enum(Object.values(ErrorCode));

export type ErrorCodeKey = "IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR" | "IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR" | "INVALID_FRIENDSHIP_ACTION_ERROR" | "MISSING_PASSWORD_ERROR" | "NOT_VERIFIED_ACCOUNT_ERROR" | "PASSWORD_RESET_TOKEN_EXPIRED_ERROR" | "PASSWORD_RESET_TOKEN_INVALID_ERROR" | "PASSWORD_VALIDATION_ERROR" | "VERIFICATION_TOKEN_EXPIRED_ERROR" | "VERIFICATION_TOKEN_INVALID_ERROR" | "EMAIL_ADDRESS_CONFLICT_ERROR" | "INVALID_CREDENTIALS_ERROR" | "NATIVE_AUTH_STRATEGY_ERROR";
