/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as publicProfileNameRouteRouteImport } from './routes/(public)/profile/$name/route'
import { Route as protectedDashboardRequestsRouteRouteImport } from './routes/(protected)/dashboard/requests/route'
import { Route as protectedDashboardFriendsRouteRouteImport } from './routes/(protected)/dashboard/friends/route'
import { Route as protectedDashboardDiscoverRouteRouteImport } from './routes/(protected)/dashboard/discover/route'
import { Route as authauthLayoutAuthLayoutRouteRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/route'
import { Route as protectedDashboardSnippetsIndexRouteImport } from './routes/(protected)/dashboard/snippets/index'
import { Route as protectedDashboardCollectionsIndexRouteImport } from './routes/(protected)/dashboard/collections/index'
import { Route as authauthLayoutAuthLayoutSignupRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/signup'
import { Route as authauthLayoutAuthLayoutLoginRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/login'
import { Route as authauthLayoutAuthLayoutForgotPasswordRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/forgot-password'
import { Route as protectedDashboardSnippetsNewRouteRouteImport } from './routes/(protected)/dashboard/snippets/new/route'
import { Route as protectedDashboardCollectionsNewRouteRouteImport } from './routes/(protected)/dashboard/collections/new/route'
import { Route as protectedDashboardSnippetsSlugIndexRouteImport } from './routes/(protected)/dashboard/snippets/$slug/index'
import { Route as protectedDashboardCollectionsSlugIndexRouteImport } from './routes/(protected)/dashboard/collections/$slug/index'
import { Route as protectedDashboardSnippetsSlugEditRouteRouteImport } from './routes/(protected)/dashboard/snippets/$slug/edit/route'
import { Route as protectedDashboardCollectionsSlugEditRouteRouteImport } from './routes/(protected)/dashboard/collections/$slug/edit/route'

const authauthLayoutRouteImport = createFileRoute('/(auth)/(auth-layout)')()

const authauthLayoutRoute = authauthLayoutRouteImport.update({
  id: '/(auth)/(auth-layout)',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRouteRoute,
} as any)
const publicProfileNameRouteRoute = publicProfileNameRouteRouteImport.update({
  id: '/(public)/profile/$name',
  path: '/profile/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRequestsRouteRoute =
  protectedDashboardRequestsRouteRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardFriendsRouteRoute =
  protectedDashboardFriendsRouteRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDiscoverRouteRoute =
  protectedDashboardDiscoverRouteRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const authauthLayoutAuthLayoutRouteRoute =
  authauthLayoutAuthLayoutRouteRouteImport.update({
    id: '/_auth-layout',
    getParentRoute: () => authauthLayoutRoute,
  } as any)
const protectedDashboardSnippetsIndexRoute =
  protectedDashboardSnippetsIndexRouteImport.update({
    id: '/snippets/',
    path: '/snippets/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsIndexRoute =
  protectedDashboardCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const authauthLayoutAuthLayoutSignupRoute =
  authauthLayoutAuthLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutLoginRoute =
  authauthLayoutAuthLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutForgotPasswordRoute =
  authauthLayoutAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const protectedDashboardSnippetsNewRouteRoute =
  protectedDashboardSnippetsNewRouteRouteImport.update({
    id: '/snippets/new',
    path: '/snippets/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsNewRouteRoute =
  protectedDashboardCollectionsNewRouteRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSnippetsSlugIndexRoute =
  protectedDashboardSnippetsSlugIndexRouteImport.update({
    id: '/snippets/$slug/',
    path: '/snippets/$slug/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsSlugIndexRoute =
  protectedDashboardCollectionsSlugIndexRouteImport.update({
    id: '/collections/$slug/',
    path: '/collections/$slug/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSnippetsSlugEditRouteRoute =
  protectedDashboardSnippetsSlugEditRouteRouteImport.update({
    id: '/snippets/$slug/edit',
    path: '/snippets/$slug/edit',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsSlugEditRouteRoute =
  protectedDashboardCollectionsSlugEditRouteRouteImport.update({
    id: '/collections/$slug/edit',
    path: '/collections/$slug/edit',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/dashboard/discover': typeof protectedDashboardDiscoverRouteRoute
  '/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/dashboard/requests': typeof protectedDashboardRequestsRouteRoute
  '/profile/$name': typeof publicProfileNameRouteRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/dashboard/collections': typeof protectedDashboardCollectionsIndexRoute
  '/dashboard/snippets': typeof protectedDashboardSnippetsIndexRoute
  '/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/dashboard/collections/$slug': typeof protectedDashboardCollectionsSlugIndexRoute
  '/dashboard/snippets/$slug': typeof protectedDashboardSnippetsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/dashboard/discover': typeof protectedDashboardDiscoverRouteRoute
  '/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/dashboard/requests': typeof protectedDashboardRequestsRouteRoute
  '/profile/$name': typeof publicProfileNameRouteRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/dashboard/collections': typeof protectedDashboardCollectionsIndexRoute
  '/dashboard/snippets': typeof protectedDashboardSnippetsIndexRoute
  '/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/dashboard/collections/$slug': typeof protectedDashboardCollectionsSlugIndexRoute
  '/dashboard/snippets/$slug': typeof protectedDashboardSnippetsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/(auth-layout)': typeof authauthLayoutRouteWithChildren
  '/(auth)/(auth-layout)/_auth-layout': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/(protected)/dashboard/discover': typeof protectedDashboardDiscoverRouteRoute
  '/(protected)/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/(protected)/dashboard/requests': typeof protectedDashboardRequestsRouteRoute
  '/(public)/profile/$name': typeof publicProfileNameRouteRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/(protected)/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/(auth)/(auth-layout)/_auth-layout/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/(auth)/(auth-layout)/_auth-layout/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/(auth)/(auth-layout)/_auth-layout/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/(protected)/dashboard/collections/': typeof protectedDashboardCollectionsIndexRoute
  '/(protected)/dashboard/snippets/': typeof protectedDashboardSnippetsIndexRoute
  '/(protected)/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/(protected)/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/(protected)/dashboard/collections/$slug/': typeof protectedDashboardCollectionsSlugIndexRoute
  '/(protected)/dashboard/snippets/$slug/': typeof protectedDashboardSnippetsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/discover'
    | '/dashboard/friends'
    | '/dashboard/requests'
    | '/profile/$name'
    | '/dashboard/'
    | '/dashboard/collections/new'
    | '/dashboard/snippets/new'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/collections'
    | '/dashboard/snippets'
    | '/dashboard/collections/$slug/edit'
    | '/dashboard/snippets/$slug/edit'
    | '/dashboard/collections/$slug'
    | '/dashboard/snippets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/discover'
    | '/dashboard/friends'
    | '/dashboard/requests'
    | '/profile/$name'
    | '/dashboard'
    | '/dashboard/collections/new'
    | '/dashboard/snippets/new'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/collections'
    | '/dashboard/snippets'
    | '/dashboard/collections/$slug/edit'
    | '/dashboard/snippets/$slug/edit'
    | '/dashboard/collections/$slug'
    | '/dashboard/snippets/$slug'
  id:
    | '__root__'
    | '/(protected)/dashboard'
    | '/(public)/'
    | '/(auth)/(auth-layout)'
    | '/(auth)/(auth-layout)/_auth-layout'
    | '/(protected)/dashboard/discover'
    | '/(protected)/dashboard/friends'
    | '/(protected)/dashboard/requests'
    | '/(public)/profile/$name'
    | '/(protected)/dashboard/'
    | '/(protected)/dashboard/collections/new'
    | '/(protected)/dashboard/snippets/new'
    | '/(auth)/(auth-layout)/_auth-layout/forgot-password'
    | '/(auth)/(auth-layout)/_auth-layout/login'
    | '/(auth)/(auth-layout)/_auth-layout/signup'
    | '/(protected)/dashboard/collections/'
    | '/(protected)/dashboard/snippets/'
    | '/(protected)/dashboard/collections/$slug/edit'
    | '/(protected)/dashboard/snippets/$slug/edit'
    | '/(protected)/dashboard/collections/$slug/'
    | '/(protected)/dashboard/snippets/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
  authauthLayoutRoute: typeof authauthLayoutRouteWithChildren
  publicProfileNameRouteRoute: typeof publicProfileNameRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/(auth-layout)': {
      id: '/(auth)/(auth-layout)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(public)/profile/$name': {
      id: '/(public)/profile/$name'
      path: '/profile/$name'
      fullPath: '/profile/$name'
      preLoaderRoute: typeof publicProfileNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/requests': {
      id: '/(protected)/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof protectedDashboardRequestsRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/friends': {
      id: '/(protected)/dashboard/friends'
      path: '/friends'
      fullPath: '/dashboard/friends'
      preLoaderRoute: typeof protectedDashboardFriendsRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/discover': {
      id: '/(protected)/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof protectedDashboardDiscoverRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout': {
      id: '/(auth)/(auth-layout)/_auth-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authauthLayoutAuthLayoutRouteRouteImport
      parentRoute: typeof authauthLayoutRoute
    }
    '/(protected)/dashboard/snippets/': {
      id: '/(protected)/dashboard/snippets/'
      path: '/snippets'
      fullPath: '/dashboard/snippets'
      preLoaderRoute: typeof protectedDashboardSnippetsIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/': {
      id: '/(protected)/dashboard/collections/'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof protectedDashboardCollectionsIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/signup': {
      id: '/(auth)/(auth-layout)/_auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authauthLayoutAuthLayoutSignupRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/login': {
      id: '/(auth)/(auth-layout)/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authauthLayoutAuthLayoutLoginRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/forgot-password': {
      id: '/(auth)/(auth-layout)/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authauthLayoutAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(protected)/dashboard/snippets/new': {
      id: '/(protected)/dashboard/snippets/new'
      path: '/snippets/new'
      fullPath: '/dashboard/snippets/new'
      preLoaderRoute: typeof protectedDashboardSnippetsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/new': {
      id: '/(protected)/dashboard/collections/new'
      path: '/collections/new'
      fullPath: '/dashboard/collections/new'
      preLoaderRoute: typeof protectedDashboardCollectionsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/snippets/$slug/': {
      id: '/(protected)/dashboard/snippets/$slug/'
      path: '/snippets/$slug'
      fullPath: '/dashboard/snippets/$slug'
      preLoaderRoute: typeof protectedDashboardSnippetsSlugIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/$slug/': {
      id: '/(protected)/dashboard/collections/$slug/'
      path: '/collections/$slug'
      fullPath: '/dashboard/collections/$slug'
      preLoaderRoute: typeof protectedDashboardCollectionsSlugIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/snippets/$slug/edit': {
      id: '/(protected)/dashboard/snippets/$slug/edit'
      path: '/snippets/$slug/edit'
      fullPath: '/dashboard/snippets/$slug/edit'
      preLoaderRoute: typeof protectedDashboardSnippetsSlugEditRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/$slug/edit': {
      id: '/(protected)/dashboard/collections/$slug/edit'
      path: '/collections/$slug/edit'
      fullPath: '/dashboard/collections/$slug/edit'
      preLoaderRoute: typeof protectedDashboardCollectionsSlugEditRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
  }
}

interface protectedDashboardRouteRouteChildren {
  protectedDashboardDiscoverRouteRoute: typeof protectedDashboardDiscoverRouteRoute
  protectedDashboardFriendsRouteRoute: typeof protectedDashboardFriendsRouteRoute
  protectedDashboardRequestsRouteRoute: typeof protectedDashboardRequestsRouteRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedDashboardCollectionsNewRouteRoute: typeof protectedDashboardCollectionsNewRouteRoute
  protectedDashboardSnippetsNewRouteRoute: typeof protectedDashboardSnippetsNewRouteRoute
  protectedDashboardCollectionsIndexRoute: typeof protectedDashboardCollectionsIndexRoute
  protectedDashboardSnippetsIndexRoute: typeof protectedDashboardSnippetsIndexRoute
  protectedDashboardCollectionsSlugEditRouteRoute: typeof protectedDashboardCollectionsSlugEditRouteRoute
  protectedDashboardSnippetsSlugEditRouteRoute: typeof protectedDashboardSnippetsSlugEditRouteRoute
  protectedDashboardCollectionsSlugIndexRoute: typeof protectedDashboardCollectionsSlugIndexRoute
  protectedDashboardSnippetsSlugIndexRoute: typeof protectedDashboardSnippetsSlugIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardDiscoverRouteRoute: protectedDashboardDiscoverRouteRoute,
    protectedDashboardFriendsRouteRoute: protectedDashboardFriendsRouteRoute,
    protectedDashboardRequestsRouteRoute: protectedDashboardRequestsRouteRoute,
    protectedDashboardIndexRoute: protectedDashboardIndexRoute,
    protectedDashboardCollectionsNewRouteRoute:
      protectedDashboardCollectionsNewRouteRoute,
    protectedDashboardSnippetsNewRouteRoute:
      protectedDashboardSnippetsNewRouteRoute,
    protectedDashboardCollectionsIndexRoute:
      protectedDashboardCollectionsIndexRoute,
    protectedDashboardSnippetsIndexRoute: protectedDashboardSnippetsIndexRoute,
    protectedDashboardCollectionsSlugEditRouteRoute:
      protectedDashboardCollectionsSlugEditRouteRoute,
    protectedDashboardSnippetsSlugEditRouteRoute:
      protectedDashboardSnippetsSlugEditRouteRoute,
    protectedDashboardCollectionsSlugIndexRoute:
      protectedDashboardCollectionsSlugIndexRoute,
    protectedDashboardSnippetsSlugIndexRoute:
      protectedDashboardSnippetsSlugIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

interface authauthLayoutAuthLayoutRouteRouteChildren {
  authauthLayoutAuthLayoutForgotPasswordRoute: typeof authauthLayoutAuthLayoutForgotPasswordRoute
  authauthLayoutAuthLayoutLoginRoute: typeof authauthLayoutAuthLayoutLoginRoute
  authauthLayoutAuthLayoutSignupRoute: typeof authauthLayoutAuthLayoutSignupRoute
}

const authauthLayoutAuthLayoutRouteRouteChildren: authauthLayoutAuthLayoutRouteRouteChildren =
  {
    authauthLayoutAuthLayoutForgotPasswordRoute:
      authauthLayoutAuthLayoutForgotPasswordRoute,
    authauthLayoutAuthLayoutLoginRoute: authauthLayoutAuthLayoutLoginRoute,
    authauthLayoutAuthLayoutSignupRoute: authauthLayoutAuthLayoutSignupRoute,
  }

const authauthLayoutAuthLayoutRouteRouteWithChildren =
  authauthLayoutAuthLayoutRouteRoute._addFileChildren(
    authauthLayoutAuthLayoutRouteRouteChildren,
  )

interface authauthLayoutRouteChildren {
  authauthLayoutAuthLayoutRouteRoute: typeof authauthLayoutAuthLayoutRouteRouteWithChildren
}

const authauthLayoutRouteChildren: authauthLayoutRouteChildren = {
  authauthLayoutAuthLayoutRouteRoute:
    authauthLayoutAuthLayoutRouteRouteWithChildren,
}

const authauthLayoutRouteWithChildren = authauthLayoutRoute._addFileChildren(
  authauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
  authauthLayoutRoute: authauthLayoutRouteWithChildren,
  publicProfileNameRouteRoute: publicProfileNameRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
