/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as publicProfileNameRouteRouteImport } from './routes/(public)/profile/$name/route'
import { Route as protectedDashboardSettingsRouteRouteImport } from './routes/(protected)/dashboard/settings/route'
import { Route as protectedDashboardFriendsRouteRouteImport } from './routes/(protected)/dashboard/friends/route'
import { Route as protectedDashboardDashboardLayoutRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/route'
import { Route as authauthLayoutAuthLayoutRouteRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/route'
import { Route as protectedDashboardSnippetsIndexRouteImport } from './routes/(protected)/dashboard/snippets/index'
import { Route as authauthLayoutAuthLayoutSignupRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/signup'
import { Route as authauthLayoutAuthLayoutPasswordResetRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/password-reset'
import { Route as authauthLayoutAuthLayoutLoginRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/login'
import { Route as authauthLayoutAuthLayoutForgotPasswordRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/forgot-password'
import { Route as authauthLayoutAuthLayoutEmailVerificationRouteImport } from './routes/(auth)/(auth-layout)/_auth-layout/email-verification'
import { Route as protectedDashboardSnippetsNewRouteRouteImport } from './routes/(protected)/dashboard/snippets/new/route'
import { Route as protectedDashboardSnippetsSlugRouteRouteImport } from './routes/(protected)/dashboard/snippets/$slug/route'
import { Route as protectedDashboardSettingsSecurityRouteRouteImport } from './routes/(protected)/dashboard/settings/security/route'
import { Route as protectedDashboardSettingsProfileRouteRouteImport } from './routes/(protected)/dashboard/settings/profile/route'
import { Route as protectedDashboardSettingsAppearanceRouteRouteImport } from './routes/(protected)/dashboard/settings/appearance/route'
import { Route as protectedDashboardCollectionsNewRouteRouteImport } from './routes/(protected)/dashboard/collections/new/route'
import { Route as protectedDashboardCollectionsSlugRouteRouteImport } from './routes/(protected)/dashboard/collections/$slug/route'
import { Route as protectedDashboardDashboardLayoutErrorBoundaryRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_error-boundary/route'
import { Route as protectedDashboardSnippetsSlugIndexRouteImport } from './routes/(protected)/dashboard/snippets/$slug/index'
import { Route as protectedDashboardCollectionsSlugIndexRouteImport } from './routes/(protected)/dashboard/collections/$slug/index'
import { Route as protectedDashboardDashboardLayoutErrorBoundaryIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_error-boundary/index'
import { Route as protectedDashboardSnippetsSlugEditRouteRouteImport } from './routes/(protected)/dashboard/snippets/$slug/edit/route'
import { Route as protectedDashboardCollectionsSlugEditRouteRouteImport } from './routes/(protected)/dashboard/collections/$slug/edit/route'
import { Route as protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_error-boundary/requests/route'
import { Route as protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_error-boundary/discover/route'
import { Route as protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_error-boundary/collections/index'

const authauthLayoutRouteImport = createFileRoute('/(auth)/(auth-layout)')()

const authauthLayoutRoute = authauthLayoutRouteImport.update({
  id: '/(auth)/(auth-layout)',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProfileNameRouteRoute = publicProfileNameRouteRouteImport.update({
  id: '/(public)/profile/$name',
  path: '/profile/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardSettingsRouteRoute =
  protectedDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardFriendsRouteRoute =
  protectedDashboardFriendsRouteRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutRouteRoute =
  protectedDashboardDashboardLayoutRouteRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const authauthLayoutAuthLayoutRouteRoute =
  authauthLayoutAuthLayoutRouteRouteImport.update({
    id: '/_auth-layout',
    getParentRoute: () => authauthLayoutRoute,
  } as any)
const protectedDashboardSnippetsIndexRoute =
  protectedDashboardSnippetsIndexRouteImport.update({
    id: '/snippets/',
    path: '/snippets/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const authauthLayoutAuthLayoutSignupRoute =
  authauthLayoutAuthLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutPasswordResetRoute =
  authauthLayoutAuthLayoutPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutLoginRoute =
  authauthLayoutAuthLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutForgotPasswordRoute =
  authauthLayoutAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const authauthLayoutAuthLayoutEmailVerificationRoute =
  authauthLayoutAuthLayoutEmailVerificationRouteImport.update({
    id: '/email-verification',
    path: '/email-verification',
    getParentRoute: () => authauthLayoutAuthLayoutRouteRoute,
  } as any)
const protectedDashboardSnippetsNewRouteRoute =
  protectedDashboardSnippetsNewRouteRouteImport.update({
    id: '/snippets/new',
    path: '/snippets/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSnippetsSlugRouteRoute =
  protectedDashboardSnippetsSlugRouteRouteImport.update({
    id: '/snippets/$slug',
    path: '/snippets/$slug',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSettingsSecurityRouteRoute =
  protectedDashboardSettingsSecurityRouteRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardSettingsProfileRouteRoute =
  protectedDashboardSettingsProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardSettingsAppearanceRouteRoute =
  protectedDashboardSettingsAppearanceRouteRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardCollectionsNewRouteRoute =
  protectedDashboardCollectionsNewRouteRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsSlugRouteRoute =
  protectedDashboardCollectionsSlugRouteRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutErrorBoundaryRouteRoute =
  protectedDashboardDashboardLayoutErrorBoundaryRouteRouteImport.update({
    id: '/_error-boundary',
    getParentRoute: () => protectedDashboardDashboardLayoutRouteRoute,
  } as any)
const protectedDashboardSnippetsSlugIndexRoute =
  protectedDashboardSnippetsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardSnippetsSlugRouteRoute,
  } as any)
const protectedDashboardCollectionsSlugIndexRoute =
  protectedDashboardCollectionsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardCollectionsSlugRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutErrorBoundaryIndexRoute =
  protectedDashboardDashboardLayoutErrorBoundaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      protectedDashboardDashboardLayoutErrorBoundaryRouteRoute,
  } as any)
const protectedDashboardSnippetsSlugEditRouteRoute =
  protectedDashboardSnippetsSlugEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => protectedDashboardSnippetsSlugRouteRoute,
  } as any)
const protectedDashboardCollectionsSlugEditRouteRoute =
  protectedDashboardCollectionsSlugEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => protectedDashboardCollectionsSlugRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute =
  protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRouteImport.update(
    {
      id: '/requests',
      path: '/requests',
      getParentRoute: () =>
        protectedDashboardDashboardLayoutErrorBoundaryRouteRoute,
    } as any,
  )
const protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute =
  protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRouteImport.update(
    {
      id: '/discover',
      path: '/discover',
      getParentRoute: () =>
        protectedDashboardDashboardLayoutErrorBoundaryRouteRoute,
    } as any,
  )
const protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute =
  protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRouteImport.update(
    {
      id: '/collections/',
      path: '/collections/',
      getParentRoute: () =>
        protectedDashboardDashboardLayoutErrorBoundaryRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/dashboard': typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRouteWithChildren
  '/': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/profile/$name': typeof publicProfileNameRouteRoute
  '/dashboard/collections/$slug': typeof protectedDashboardCollectionsSlugRouteRouteWithChildren
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/settings/appearance': typeof protectedDashboardSettingsAppearanceRouteRoute
  '/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/dashboard/settings/security': typeof protectedDashboardSettingsSecurityRouteRoute
  '/dashboard/snippets/$slug': typeof protectedDashboardSnippetsSlugRouteRouteWithChildren
  '/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/email-verification': typeof authauthLayoutAuthLayoutEmailVerificationRoute
  '/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/password-reset': typeof authauthLayoutAuthLayoutPasswordResetRoute
  '/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/dashboard/snippets': typeof protectedDashboardSnippetsIndexRoute
  '/dashboard/discover': typeof protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute
  '/dashboard/requests': typeof protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute
  '/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/dashboard/': typeof protectedDashboardDashboardLayoutErrorBoundaryIndexRoute
  '/dashboard/collections/$slug/': typeof protectedDashboardCollectionsSlugIndexRoute
  '/dashboard/snippets/$slug/': typeof protectedDashboardSnippetsSlugIndexRoute
  '/dashboard/collections': typeof protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof protectedDashboardDashboardLayoutErrorBoundaryIndexRoute
  '/': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/profile/$name': typeof publicProfileNameRouteRoute
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/settings/appearance': typeof protectedDashboardSettingsAppearanceRouteRoute
  '/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/dashboard/settings/security': typeof protectedDashboardSettingsSecurityRouteRoute
  '/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/email-verification': typeof authauthLayoutAuthLayoutEmailVerificationRoute
  '/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/password-reset': typeof authauthLayoutAuthLayoutPasswordResetRoute
  '/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/dashboard/snippets': typeof protectedDashboardSnippetsIndexRoute
  '/dashboard/discover': typeof protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute
  '/dashboard/requests': typeof protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute
  '/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/dashboard/collections/$slug': typeof protectedDashboardCollectionsSlugIndexRoute
  '/dashboard/snippets/$slug': typeof protectedDashboardSnippetsSlugIndexRoute
  '/dashboard/collections': typeof protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/(auth-layout)': typeof authauthLayoutRouteWithChildren
  '/(auth)/(auth-layout)/_auth-layout': typeof authauthLayoutAuthLayoutRouteRouteWithChildren
  '/(protected)/dashboard/_dashboard-layout': typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  '/(protected)/dashboard/friends': typeof protectedDashboardFriendsRouteRoute
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/(public)/profile/$name': typeof publicProfileNameRouteRoute
  '/(protected)/dashboard/_dashboard-layout/_error-boundary': typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRouteWithChildren
  '/(protected)/dashboard/collections/$slug': typeof protectedDashboardCollectionsSlugRouteRouteWithChildren
  '/(protected)/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/(protected)/dashboard/settings/appearance': typeof protectedDashboardSettingsAppearanceRouteRoute
  '/(protected)/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/(protected)/dashboard/settings/security': typeof protectedDashboardSettingsSecurityRouteRoute
  '/(protected)/dashboard/snippets/$slug': typeof protectedDashboardSnippetsSlugRouteRouteWithChildren
  '/(protected)/dashboard/snippets/new': typeof protectedDashboardSnippetsNewRouteRoute
  '/(auth)/(auth-layout)/_auth-layout/email-verification': typeof authauthLayoutAuthLayoutEmailVerificationRoute
  '/(auth)/(auth-layout)/_auth-layout/forgot-password': typeof authauthLayoutAuthLayoutForgotPasswordRoute
  '/(auth)/(auth-layout)/_auth-layout/login': typeof authauthLayoutAuthLayoutLoginRoute
  '/(auth)/(auth-layout)/_auth-layout/password-reset': typeof authauthLayoutAuthLayoutPasswordResetRoute
  '/(auth)/(auth-layout)/_auth-layout/signup': typeof authauthLayoutAuthLayoutSignupRoute
  '/(protected)/dashboard/snippets/': typeof protectedDashboardSnippetsIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_error-boundary/discover': typeof protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute
  '/(protected)/dashboard/_dashboard-layout/_error-boundary/requests': typeof protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute
  '/(protected)/dashboard/collections/$slug/edit': typeof protectedDashboardCollectionsSlugEditRouteRoute
  '/(protected)/dashboard/snippets/$slug/edit': typeof protectedDashboardSnippetsSlugEditRouteRoute
  '/(protected)/dashboard/_dashboard-layout/_error-boundary/': typeof protectedDashboardDashboardLayoutErrorBoundaryIndexRoute
  '/(protected)/dashboard/collections/$slug/': typeof protectedDashboardCollectionsSlugIndexRoute
  '/(protected)/dashboard/snippets/$slug/': typeof protectedDashboardSnippetsSlugIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_error-boundary/collections/': typeof protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/friends'
    | '/dashboard/settings'
    | '/profile/$name'
    | '/dashboard/collections/$slug'
    | '/dashboard/collections/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/snippets/$slug'
    | '/dashboard/snippets/new'
    | '/email-verification'
    | '/forgot-password'
    | '/login'
    | '/password-reset'
    | '/signup'
    | '/dashboard/snippets'
    | '/dashboard/discover'
    | '/dashboard/requests'
    | '/dashboard/collections/$slug/edit'
    | '/dashboard/snippets/$slug/edit'
    | '/dashboard/'
    | '/dashboard/collections/$slug/'
    | '/dashboard/snippets/$slug/'
    | '/dashboard/collections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/'
    | '/dashboard/friends'
    | '/dashboard/settings'
    | '/profile/$name'
    | '/dashboard/collections/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/snippets/new'
    | '/email-verification'
    | '/forgot-password'
    | '/login'
    | '/password-reset'
    | '/signup'
    | '/dashboard/snippets'
    | '/dashboard/discover'
    | '/dashboard/requests'
    | '/dashboard/collections/$slug/edit'
    | '/dashboard/snippets/$slug/edit'
    | '/dashboard/collections/$slug'
    | '/dashboard/snippets/$slug'
    | '/dashboard/collections'
  id:
    | '__root__'
    | '/(protected)/dashboard'
    | '/(public)/'
    | '/(auth)/(auth-layout)'
    | '/(auth)/(auth-layout)/_auth-layout'
    | '/(protected)/dashboard/_dashboard-layout'
    | '/(protected)/dashboard/friends'
    | '/(protected)/dashboard/settings'
    | '/(public)/profile/$name'
    | '/(protected)/dashboard/_dashboard-layout/_error-boundary'
    | '/(protected)/dashboard/collections/$slug'
    | '/(protected)/dashboard/collections/new'
    | '/(protected)/dashboard/settings/appearance'
    | '/(protected)/dashboard/settings/profile'
    | '/(protected)/dashboard/settings/security'
    | '/(protected)/dashboard/snippets/$slug'
    | '/(protected)/dashboard/snippets/new'
    | '/(auth)/(auth-layout)/_auth-layout/email-verification'
    | '/(auth)/(auth-layout)/_auth-layout/forgot-password'
    | '/(auth)/(auth-layout)/_auth-layout/login'
    | '/(auth)/(auth-layout)/_auth-layout/password-reset'
    | '/(auth)/(auth-layout)/_auth-layout/signup'
    | '/(protected)/dashboard/snippets/'
    | '/(protected)/dashboard/_dashboard-layout/_error-boundary/discover'
    | '/(protected)/dashboard/_dashboard-layout/_error-boundary/requests'
    | '/(protected)/dashboard/collections/$slug/edit'
    | '/(protected)/dashboard/snippets/$slug/edit'
    | '/(protected)/dashboard/_dashboard-layout/_error-boundary/'
    | '/(protected)/dashboard/collections/$slug/'
    | '/(protected)/dashboard/snippets/$slug/'
    | '/(protected)/dashboard/_dashboard-layout/_error-boundary/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
  authauthLayoutRoute: typeof authauthLayoutRouteWithChildren
  publicProfileNameRouteRoute: typeof publicProfileNameRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/(auth-layout)': {
      id: '/(auth)/(auth-layout)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/profile/$name': {
      id: '/(public)/profile/$name'
      path: '/profile/$name'
      fullPath: '/profile/$name'
      preLoaderRoute: typeof publicProfileNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/friends': {
      id: '/(protected)/dashboard/friends'
      path: '/friends'
      fullPath: '/dashboard/friends'
      preLoaderRoute: typeof protectedDashboardFriendsRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout': {
      id: '/(protected)/dashboard/_dashboard-layout'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout': {
      id: '/(auth)/(auth-layout)/_auth-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authauthLayoutAuthLayoutRouteRouteImport
      parentRoute: typeof authauthLayoutRoute
    }
    '/(protected)/dashboard/snippets/': {
      id: '/(protected)/dashboard/snippets/'
      path: '/snippets'
      fullPath: '/dashboard/snippets'
      preLoaderRoute: typeof protectedDashboardSnippetsIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/signup': {
      id: '/(auth)/(auth-layout)/_auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authauthLayoutAuthLayoutSignupRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/password-reset': {
      id: '/(auth)/(auth-layout)/_auth-layout/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authauthLayoutAuthLayoutPasswordResetRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/login': {
      id: '/(auth)/(auth-layout)/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authauthLayoutAuthLayoutLoginRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/forgot-password': {
      id: '/(auth)/(auth-layout)/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authauthLayoutAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(auth)/(auth-layout)/_auth-layout/email-verification': {
      id: '/(auth)/(auth-layout)/_auth-layout/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof authauthLayoutAuthLayoutEmailVerificationRouteImport
      parentRoute: typeof authauthLayoutAuthLayoutRouteRoute
    }
    '/(protected)/dashboard/snippets/new': {
      id: '/(protected)/dashboard/snippets/new'
      path: '/snippets/new'
      fullPath: '/dashboard/snippets/new'
      preLoaderRoute: typeof protectedDashboardSnippetsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/snippets/$slug': {
      id: '/(protected)/dashboard/snippets/$slug'
      path: '/snippets/$slug'
      fullPath: '/dashboard/snippets/$slug'
      preLoaderRoute: typeof protectedDashboardSnippetsSlugRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/settings/security': {
      id: '/(protected)/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof protectedDashboardSettingsSecurityRouteRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/settings/profile': {
      id: '/(protected)/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof protectedDashboardSettingsProfileRouteRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/settings/appearance': {
      id: '/(protected)/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof protectedDashboardSettingsAppearanceRouteRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/collections/new': {
      id: '/(protected)/dashboard/collections/new'
      path: '/collections/new'
      fullPath: '/dashboard/collections/new'
      preLoaderRoute: typeof protectedDashboardCollectionsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/$slug': {
      id: '/(protected)/dashboard/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/dashboard/collections/$slug'
      preLoaderRoute: typeof protectedDashboardCollectionsSlugRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_error-boundary': {
      id: '/(protected)/dashboard/_dashboard-layout/_error-boundary'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutRouteRoute
    }
    '/(protected)/dashboard/snippets/$slug/': {
      id: '/(protected)/dashboard/snippets/$slug/'
      path: '/'
      fullPath: '/dashboard/snippets/$slug/'
      preLoaderRoute: typeof protectedDashboardSnippetsSlugIndexRouteImport
      parentRoute: typeof protectedDashboardSnippetsSlugRouteRoute
    }
    '/(protected)/dashboard/collections/$slug/': {
      id: '/(protected)/dashboard/collections/$slug/'
      path: '/'
      fullPath: '/dashboard/collections/$slug/'
      preLoaderRoute: typeof protectedDashboardCollectionsSlugIndexRouteImport
      parentRoute: typeof protectedDashboardCollectionsSlugRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_error-boundary/': {
      id: '/(protected)/dashboard/_dashboard-layout/_error-boundary/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRoute
    }
    '/(protected)/dashboard/snippets/$slug/edit': {
      id: '/(protected)/dashboard/snippets/$slug/edit'
      path: '/edit'
      fullPath: '/dashboard/snippets/$slug/edit'
      preLoaderRoute: typeof protectedDashboardSnippetsSlugEditRouteRouteImport
      parentRoute: typeof protectedDashboardSnippetsSlugRouteRoute
    }
    '/(protected)/dashboard/collections/$slug/edit': {
      id: '/(protected)/dashboard/collections/$slug/edit'
      path: '/edit'
      fullPath: '/dashboard/collections/$slug/edit'
      preLoaderRoute: typeof protectedDashboardCollectionsSlugEditRouteRouteImport
      parentRoute: typeof protectedDashboardCollectionsSlugRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_error-boundary/requests': {
      id: '/(protected)/dashboard/_dashboard-layout/_error-boundary/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_error-boundary/discover': {
      id: '/(protected)/dashboard/_dashboard-layout/_error-boundary/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_error-boundary/collections/': {
      id: '/(protected)/dashboard/_dashboard-layout/_error-boundary/collections/'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRoute
    }
  }
}

interface protectedDashboardDashboardLayoutErrorBoundaryRouteRouteChildren {
  protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute
  protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute
  protectedDashboardDashboardLayoutErrorBoundaryIndexRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryIndexRoute
  protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute
}

const protectedDashboardDashboardLayoutErrorBoundaryRouteRouteChildren: protectedDashboardDashboardLayoutErrorBoundaryRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute:
      protectedDashboardDashboardLayoutErrorBoundaryDiscoverRouteRoute,
    protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute:
      protectedDashboardDashboardLayoutErrorBoundaryRequestsRouteRoute,
    protectedDashboardDashboardLayoutErrorBoundaryIndexRoute:
      protectedDashboardDashboardLayoutErrorBoundaryIndexRoute,
    protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute:
      protectedDashboardDashboardLayoutErrorBoundaryCollectionsIndexRoute,
  }

const protectedDashboardDashboardLayoutErrorBoundaryRouteRouteWithChildren =
  protectedDashboardDashboardLayoutErrorBoundaryRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutErrorBoundaryRouteRouteChildren,
  )

interface protectedDashboardDashboardLayoutRouteRouteChildren {
  protectedDashboardDashboardLayoutErrorBoundaryRouteRoute: typeof protectedDashboardDashboardLayoutErrorBoundaryRouteRouteWithChildren
}

const protectedDashboardDashboardLayoutRouteRouteChildren: protectedDashboardDashboardLayoutRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutErrorBoundaryRouteRoute:
      protectedDashboardDashboardLayoutErrorBoundaryRouteRouteWithChildren,
  }

const protectedDashboardDashboardLayoutRouteRouteWithChildren =
  protectedDashboardDashboardLayoutRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutRouteRouteChildren,
  )

interface protectedDashboardSettingsRouteRouteChildren {
  protectedDashboardSettingsAppearanceRouteRoute: typeof protectedDashboardSettingsAppearanceRouteRoute
  protectedDashboardSettingsProfileRouteRoute: typeof protectedDashboardSettingsProfileRouteRoute
  protectedDashboardSettingsSecurityRouteRoute: typeof protectedDashboardSettingsSecurityRouteRoute
}

const protectedDashboardSettingsRouteRouteChildren: protectedDashboardSettingsRouteRouteChildren =
  {
    protectedDashboardSettingsAppearanceRouteRoute:
      protectedDashboardSettingsAppearanceRouteRoute,
    protectedDashboardSettingsProfileRouteRoute:
      protectedDashboardSettingsProfileRouteRoute,
    protectedDashboardSettingsSecurityRouteRoute:
      protectedDashboardSettingsSecurityRouteRoute,
  }

const protectedDashboardSettingsRouteRouteWithChildren =
  protectedDashboardSettingsRouteRoute._addFileChildren(
    protectedDashboardSettingsRouteRouteChildren,
  )

interface protectedDashboardCollectionsSlugRouteRouteChildren {
  protectedDashboardCollectionsSlugEditRouteRoute: typeof protectedDashboardCollectionsSlugEditRouteRoute
  protectedDashboardCollectionsSlugIndexRoute: typeof protectedDashboardCollectionsSlugIndexRoute
}

const protectedDashboardCollectionsSlugRouteRouteChildren: protectedDashboardCollectionsSlugRouteRouteChildren =
  {
    protectedDashboardCollectionsSlugEditRouteRoute:
      protectedDashboardCollectionsSlugEditRouteRoute,
    protectedDashboardCollectionsSlugIndexRoute:
      protectedDashboardCollectionsSlugIndexRoute,
  }

const protectedDashboardCollectionsSlugRouteRouteWithChildren =
  protectedDashboardCollectionsSlugRouteRoute._addFileChildren(
    protectedDashboardCollectionsSlugRouteRouteChildren,
  )

interface protectedDashboardSnippetsSlugRouteRouteChildren {
  protectedDashboardSnippetsSlugEditRouteRoute: typeof protectedDashboardSnippetsSlugEditRouteRoute
  protectedDashboardSnippetsSlugIndexRoute: typeof protectedDashboardSnippetsSlugIndexRoute
}

const protectedDashboardSnippetsSlugRouteRouteChildren: protectedDashboardSnippetsSlugRouteRouteChildren =
  {
    protectedDashboardSnippetsSlugEditRouteRoute:
      protectedDashboardSnippetsSlugEditRouteRoute,
    protectedDashboardSnippetsSlugIndexRoute:
      protectedDashboardSnippetsSlugIndexRoute,
  }

const protectedDashboardSnippetsSlugRouteRouteWithChildren =
  protectedDashboardSnippetsSlugRouteRoute._addFileChildren(
    protectedDashboardSnippetsSlugRouteRouteChildren,
  )

interface protectedDashboardRouteRouteChildren {
  protectedDashboardDashboardLayoutRouteRoute: typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  protectedDashboardFriendsRouteRoute: typeof protectedDashboardFriendsRouteRoute
  protectedDashboardSettingsRouteRoute: typeof protectedDashboardSettingsRouteRouteWithChildren
  protectedDashboardCollectionsSlugRouteRoute: typeof protectedDashboardCollectionsSlugRouteRouteWithChildren
  protectedDashboardCollectionsNewRouteRoute: typeof protectedDashboardCollectionsNewRouteRoute
  protectedDashboardSnippetsSlugRouteRoute: typeof protectedDashboardSnippetsSlugRouteRouteWithChildren
  protectedDashboardSnippetsNewRouteRoute: typeof protectedDashboardSnippetsNewRouteRoute
  protectedDashboardSnippetsIndexRoute: typeof protectedDashboardSnippetsIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutRouteRoute:
      protectedDashboardDashboardLayoutRouteRouteWithChildren,
    protectedDashboardFriendsRouteRoute: protectedDashboardFriendsRouteRoute,
    protectedDashboardSettingsRouteRoute:
      protectedDashboardSettingsRouteRouteWithChildren,
    protectedDashboardCollectionsSlugRouteRoute:
      protectedDashboardCollectionsSlugRouteRouteWithChildren,
    protectedDashboardCollectionsNewRouteRoute:
      protectedDashboardCollectionsNewRouteRoute,
    protectedDashboardSnippetsSlugRouteRoute:
      protectedDashboardSnippetsSlugRouteRouteWithChildren,
    protectedDashboardSnippetsNewRouteRoute:
      protectedDashboardSnippetsNewRouteRoute,
    protectedDashboardSnippetsIndexRoute: protectedDashboardSnippetsIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

interface authauthLayoutAuthLayoutRouteRouteChildren {
  authauthLayoutAuthLayoutEmailVerificationRoute: typeof authauthLayoutAuthLayoutEmailVerificationRoute
  authauthLayoutAuthLayoutForgotPasswordRoute: typeof authauthLayoutAuthLayoutForgotPasswordRoute
  authauthLayoutAuthLayoutLoginRoute: typeof authauthLayoutAuthLayoutLoginRoute
  authauthLayoutAuthLayoutPasswordResetRoute: typeof authauthLayoutAuthLayoutPasswordResetRoute
  authauthLayoutAuthLayoutSignupRoute: typeof authauthLayoutAuthLayoutSignupRoute
}

const authauthLayoutAuthLayoutRouteRouteChildren: authauthLayoutAuthLayoutRouteRouteChildren =
  {
    authauthLayoutAuthLayoutEmailVerificationRoute:
      authauthLayoutAuthLayoutEmailVerificationRoute,
    authauthLayoutAuthLayoutForgotPasswordRoute:
      authauthLayoutAuthLayoutForgotPasswordRoute,
    authauthLayoutAuthLayoutLoginRoute: authauthLayoutAuthLayoutLoginRoute,
    authauthLayoutAuthLayoutPasswordResetRoute:
      authauthLayoutAuthLayoutPasswordResetRoute,
    authauthLayoutAuthLayoutSignupRoute: authauthLayoutAuthLayoutSignupRoute,
  }

const authauthLayoutAuthLayoutRouteRouteWithChildren =
  authauthLayoutAuthLayoutRouteRoute._addFileChildren(
    authauthLayoutAuthLayoutRouteRouteChildren,
  )

interface authauthLayoutRouteChildren {
  authauthLayoutAuthLayoutRouteRoute: typeof authauthLayoutAuthLayoutRouteRouteWithChildren
}

const authauthLayoutRouteChildren: authauthLayoutRouteChildren = {
  authauthLayoutAuthLayoutRouteRoute:
    authauthLayoutAuthLayoutRouteRouteWithChildren,
}

const authauthLayoutRouteWithChildren = authauthLayoutRoute._addFileChildren(
  authauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
  authauthLayoutRoute: authauthLayoutRouteWithChildren,
  publicProfileNameRouteRoute: publicProfileNameRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
