services:
  postgres_db:
    image: postgres:16-alpine
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: snippetly
      POSTGRES_USER: snippetly
      POSTGRES_PASSWORD: snippetly
    labels:
      - "io.snippetly.create.name=snippetly"

volumes:
  postgres_db_data:
    driver: local
    labels:
      - "io.snippetly.create.name=snippetly"
