packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    'zod': '^4.1.13'

catalogs:
    tooling:
        'typescript': '^5.9.2'
        'eslint': '^9.39.1'
        'concurrently': '^9.2.1'
        'ts-node': '^10.9.2'
        'tsconfig-paths': '^4.2.0'
        '@types/node': '^20.11.19'
        'prettier': '^3.2.5'
        'rimraf': '^5.0.5'
    testing:
        'vitest': '^3.2.4'
