/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authAuthLayoutRouteRouteImport } from './routes/(auth)/_auth-layout/route'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicGoodbyeRouteImport } from './routes/(public)/goodbye'
import { Route as authAuthLayoutAccountVerificationRouteImport } from './routes/(auth)/_auth-layout/account-verification'
import { Route as authAuthLayoutForgotPasswordRouteImport } from './routes/(auth)/_auth-layout/forgot-password'
import { Route as authAuthLayoutPasswordResetRouteImport } from './routes/(auth)/_auth-layout/password-reset'
import { Route as authAuthLayoutRegisterAccountRouteImport } from './routes/(auth)/_auth-layout/register-account'
import { Route as authAuthLayoutSignInRouteImport } from './routes/(auth)/_auth-layout/sign-in'
import { Route as protectedDashboardDashboardLayoutRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/route'
import { Route as protectedDashboardSettingsRouteRouteImport } from './routes/(protected)/dashboard/settings/route'
import { Route as publicOfflineIndexRouteImport } from './routes/(public)/offline/index'
import { Route as publicOfflineIdRouteImport } from './routes/(public)/offline/$id'
import { Route as publicProfileIdRouteRouteImport } from './routes/(public)/profile/$id/route'
import { Route as protectedDashboardDashboardLayoutBoundaryRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/route'
import { Route as protectedDashboardCollectionsIdRouteRouteImport } from './routes/(protected)/dashboard/collections/$id/route'
import { Route as protectedDashboardCollectionsNewRouteRouteImport } from './routes/(protected)/dashboard/collections/new/route'
import { Route as protectedDashboardSettingsProfileRouteRouteImport } from './routes/(protected)/dashboard/settings/profile/route'
import { Route as protectedDashboardSnippetsIdRouteRouteImport } from './routes/(protected)/dashboard/snippets/$id/route'
import { Route as protectedDashboardDashboardLayoutBoundaryIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/index'
import { Route as protectedDashboardDashboardLayoutBoundaryRequestsRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/requests/route'
import { Route as protectedDashboardCollectionsIdIndexRouteImport } from './routes/(protected)/dashboard/collections/$id/index'
import { Route as protectedDashboardSettingsAppearanceIndexRouteImport } from './routes/(protected)/dashboard/settings/appearance/index'
import { Route as protectedDashboardSettingsSecurityIndexRouteImport } from './routes/(protected)/dashboard/settings/security/index'
import { Route as protectedDashboardSnippetsIdIndexRouteImport } from './routes/(protected)/dashboard/snippets/$id/index'
import { Route as protectedDashboardSnippetsNewIndexRouteImport } from './routes/(protected)/dashboard/snippets/new/index'
import { Route as protectedDashboardDashboardLayoutBoundaryCollectionsIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/collections/index'
import { Route as protectedDashboardDashboardLayoutBoundaryDiscoverIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/discover/index'
import { Route as protectedDashboardDashboardLayoutBoundaryFriendsIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/friends/index'
import { Route as protectedDashboardDashboardLayoutBoundarySnippetsIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/snippets/index'
import { Route as protectedDashboardCollectionsIdEditIndexRouteImport } from './routes/(protected)/dashboard/collections/$id/edit/index'
import { Route as protectedDashboardSnippetsIdEditIndexRouteImport } from './routes/(protected)/dashboard/snippets/$id/edit/index'

const authAuthLayoutRouteRoute = authAuthLayoutRouteRouteImport.update({
  id: '/(auth)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGoodbyeRoute = publicGoodbyeRouteImport.update({
  id: '/(public)/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutAccountVerificationRoute =
  authAuthLayoutAccountVerificationRouteImport.update({
    id: '/account-verification',
    path: '/account-verification',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutForgotPasswordRoute =
  authAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutPasswordResetRoute =
  authAuthLayoutPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutRegisterAccountRoute =
  authAuthLayoutRegisterAccountRouteImport.update({
    id: '/register-account',
    path: '/register-account',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutSignInRoute = authAuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)
const protectedDashboardDashboardLayoutRouteRoute =
  protectedDashboardDashboardLayoutRouteRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSettingsRouteRoute =
  protectedDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const publicOfflineIndexRoute = publicOfflineIndexRouteImport.update({
  id: '/(public)/offline/',
  path: '/offline/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOfflineIdRoute = publicOfflineIdRouteImport.update({
  id: '/(public)/offline/$id',
  path: '/offline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProfileIdRouteRoute = publicProfileIdRouteRouteImport.update({
  id: '/(public)/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardDashboardLayoutBoundaryRouteRoute =
  protectedDashboardDashboardLayoutBoundaryRouteRouteImport.update({
    id: '/_boundary',
    getParentRoute: () => protectedDashboardDashboardLayoutRouteRoute,
  } as any)
const protectedDashboardCollectionsIdRouteRoute =
  protectedDashboardCollectionsIdRouteRouteImport.update({
    id: '/collections/$id',
    path: '/collections/$id',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsNewRouteRoute =
  protectedDashboardCollectionsNewRouteRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardSettingsProfileRouteRoute =
  protectedDashboardSettingsProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardSnippetsIdRouteRoute =
  protectedDashboardSnippetsIdRouteRouteImport.update({
    id: '/snippets/$id',
    path: '/snippets/$id',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryIndexRoute =
  protectedDashboardDashboardLayoutBoundaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute =
  protectedDashboardDashboardLayoutBoundaryRequestsRouteRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardCollectionsIdIndexRoute =
  protectedDashboardCollectionsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardCollectionsIdRouteRoute,
  } as any)
const protectedDashboardSettingsAppearanceIndexRoute =
  protectedDashboardSettingsAppearanceIndexRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardSettingsSecurityIndexRoute =
  protectedDashboardSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => protectedDashboardSettingsRouteRoute,
  } as any)
const protectedDashboardSnippetsIdIndexRoute =
  protectedDashboardSnippetsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardSnippetsIdRouteRoute,
  } as any)
const protectedDashboardSnippetsNewIndexRoute =
  protectedDashboardSnippetsNewIndexRouteImport.update({
    id: '/snippets/new/',
    path: '/snippets/new/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute =
  protectedDashboardDashboardLayoutBoundaryCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute =
  protectedDashboardDashboardLayoutBoundaryDiscoverIndexRouteImport.update({
    id: '/discover/',
    path: '/discover/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute =
  protectedDashboardDashboardLayoutBoundaryFriendsIndexRouteImport.update({
    id: '/friends/',
    path: '/friends/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute =
  protectedDashboardDashboardLayoutBoundarySnippetsIndexRouteImport.update({
    id: '/snippets/',
    path: '/snippets/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardCollectionsIdEditIndexRoute =
  protectedDashboardCollectionsIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => protectedDashboardCollectionsIdRouteRoute,
  } as any)
const protectedDashboardSnippetsIdEditIndexRoute =
  protectedDashboardSnippetsIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => protectedDashboardSnippetsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/goodbye': typeof publicGoodbyeRoute
  '/': typeof publicIndexRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/profile/$id': typeof publicProfileIdRouteRoute
  '/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/offline/$id': typeof publicOfflineIdRoute
  '/offline/': typeof publicOfflineIndexRoute
  '/dashboard/collections/$id': typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/dashboard/snippets/$id': typeof protectedDashboardSnippetsIdRouteRouteWithChildren
  '/dashboard/requests': typeof protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute
  '/dashboard/': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/dashboard/collections/$id/': typeof protectedDashboardCollectionsIdIndexRoute
  '/dashboard/settings/appearance/': typeof protectedDashboardSettingsAppearanceIndexRoute
  '/dashboard/settings/security/': typeof protectedDashboardSettingsSecurityIndexRoute
  '/dashboard/snippets/$id/': typeof protectedDashboardSnippetsIdIndexRoute
  '/dashboard/snippets/new/': typeof protectedDashboardSnippetsNewIndexRoute
  '/dashboard/collections/': typeof protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute
  '/dashboard/discover/': typeof protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute
  '/dashboard/friends/': typeof protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute
  '/dashboard/snippets/': typeof protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute
  '/dashboard/collections/$id/edit/': typeof protectedDashboardCollectionsIdEditIndexRoute
  '/dashboard/snippets/$id/edit/': typeof protectedDashboardSnippetsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/': typeof publicIndexRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/profile/$id': typeof publicProfileIdRouteRoute
  '/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/offline/$id': typeof publicOfflineIdRoute
  '/offline': typeof publicOfflineIndexRoute
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/dashboard/requests': typeof protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute
  '/dashboard/collections/$id': typeof protectedDashboardCollectionsIdIndexRoute
  '/dashboard/settings/appearance': typeof protectedDashboardSettingsAppearanceIndexRoute
  '/dashboard/settings/security': typeof protectedDashboardSettingsSecurityIndexRoute
  '/dashboard/snippets/$id': typeof protectedDashboardSnippetsIdIndexRoute
  '/dashboard/snippets/new': typeof protectedDashboardSnippetsNewIndexRoute
  '/dashboard/collections': typeof protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute
  '/dashboard/discover': typeof protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute
  '/dashboard/friends': typeof protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute
  '/dashboard/snippets': typeof protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute
  '/dashboard/collections/$id/edit': typeof protectedDashboardCollectionsIdEditIndexRoute
  '/dashboard/snippets/$id/edit': typeof protectedDashboardSnippetsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(public)/goodbye': typeof publicGoodbyeRoute
  '/(public)/': typeof publicIndexRoute
  '/(protected)/dashboard/_dashboard-layout': typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRouteRouteWithChildren
  '/(public)/profile/$id': typeof publicProfileIdRouteRoute
  '/(auth)/_auth-layout/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/(auth)/_auth-layout/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/(auth)/_auth-layout/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/(auth)/_auth-layout/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/(auth)/_auth-layout/sign-in': typeof authAuthLayoutSignInRoute
  '/(public)/offline/$id': typeof publicOfflineIdRoute
  '/(public)/offline/': typeof publicOfflineIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary': typeof protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren
  '/(protected)/dashboard/collections/$id': typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  '/(protected)/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/(protected)/dashboard/settings/profile': typeof protectedDashboardSettingsProfileRouteRoute
  '/(protected)/dashboard/snippets/$id': typeof protectedDashboardSnippetsIdRouteRouteWithChildren
  '/(protected)/dashboard/_dashboard-layout/_boundary/requests': typeof protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/(protected)/dashboard/collections/$id/': typeof protectedDashboardCollectionsIdIndexRoute
  '/(protected)/dashboard/settings/appearance/': typeof protectedDashboardSettingsAppearanceIndexRoute
  '/(protected)/dashboard/settings/security/': typeof protectedDashboardSettingsSecurityIndexRoute
  '/(protected)/dashboard/snippets/$id/': typeof protectedDashboardSnippetsIdIndexRoute
  '/(protected)/dashboard/snippets/new/': typeof protectedDashboardSnippetsNewIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/collections/': typeof protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/discover/': typeof protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/friends/': typeof protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/snippets/': typeof protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute
  '/(protected)/dashboard/collections/$id/edit/': typeof protectedDashboardCollectionsIdEditIndexRoute
  '/(protected)/dashboard/snippets/$id/edit/': typeof protectedDashboardSnippetsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/goodbye'
    | '/'
    | '/dashboard/settings'
    | '/profile/$id'
    | '/account-verification'
    | '/forgot-password'
    | '/password-reset'
    | '/register-account'
    | '/sign-in'
    | '/offline/$id'
    | '/offline/'
    | '/dashboard/collections/$id'
    | '/dashboard/collections/new'
    | '/dashboard/settings/profile'
    | '/dashboard/snippets/$id'
    | '/dashboard/requests'
    | '/dashboard/'
    | '/dashboard/collections/$id/'
    | '/dashboard/settings/appearance/'
    | '/dashboard/settings/security/'
    | '/dashboard/snippets/$id/'
    | '/dashboard/snippets/new/'
    | '/dashboard/collections/'
    | '/dashboard/discover/'
    | '/dashboard/friends/'
    | '/dashboard/snippets/'
    | '/dashboard/collections/$id/edit/'
    | '/dashboard/snippets/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/goodbye'
    | '/'
    | '/dashboard/settings'
    | '/profile/$id'
    | '/account-verification'
    | '/forgot-password'
    | '/password-reset'
    | '/register-account'
    | '/sign-in'
    | '/offline/$id'
    | '/offline'
    | '/dashboard/collections/new'
    | '/dashboard/settings/profile'
    | '/dashboard/requests'
    | '/dashboard/collections/$id'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/security'
    | '/dashboard/snippets/$id'
    | '/dashboard/snippets/new'
    | '/dashboard/collections'
    | '/dashboard/discover'
    | '/dashboard/friends'
    | '/dashboard/snippets'
    | '/dashboard/collections/$id/edit'
    | '/dashboard/snippets/$id/edit'
  id:
    | '__root__'
    | '/(auth)/_auth-layout'
    | '/(protected)/dashboard'
    | '/(public)/goodbye'
    | '/(public)/'
    | '/(protected)/dashboard/_dashboard-layout'
    | '/(protected)/dashboard/settings'
    | '/(public)/profile/$id'
    | '/(auth)/_auth-layout/account-verification'
    | '/(auth)/_auth-layout/forgot-password'
    | '/(auth)/_auth-layout/password-reset'
    | '/(auth)/_auth-layout/register-account'
    | '/(auth)/_auth-layout/sign-in'
    | '/(public)/offline/$id'
    | '/(public)/offline/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary'
    | '/(protected)/dashboard/collections/$id'
    | '/(protected)/dashboard/collections/new'
    | '/(protected)/dashboard/settings/profile'
    | '/(protected)/dashboard/snippets/$id'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/requests'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/'
    | '/(protected)/dashboard/collections/$id/'
    | '/(protected)/dashboard/settings/appearance/'
    | '/(protected)/dashboard/settings/security/'
    | '/(protected)/dashboard/snippets/$id/'
    | '/(protected)/dashboard/snippets/new/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/collections/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/discover/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/friends/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/snippets/'
    | '/(protected)/dashboard/collections/$id/edit/'
    | '/(protected)/dashboard/snippets/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthLayoutRouteRoute: typeof authAuthLayoutRouteRouteWithChildren
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  publicGoodbyeRoute: typeof publicGoodbyeRoute
  publicIndexRoute: typeof publicIndexRoute
  publicProfileIdRouteRoute: typeof publicProfileIdRouteRoute
  publicOfflineIdRoute: typeof publicOfflineIdRoute
  publicOfflineIndexRoute: typeof publicOfflineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/goodbye': {
      id: '/(public)/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof publicGoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout/account-verification': {
      id: '/(auth)/_auth-layout/account-verification'
      path: '/account-verification'
      fullPath: '/account-verification'
      preLoaderRoute: typeof authAuthLayoutAccountVerificationRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/forgot-password': {
      id: '/(auth)/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/password-reset': {
      id: '/(auth)/_auth-layout/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authAuthLayoutPasswordResetRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/register-account': {
      id: '/(auth)/_auth-layout/register-account'
      path: '/register-account'
      fullPath: '/register-account'
      preLoaderRoute: typeof authAuthLayoutRegisterAccountRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/sign-in': {
      id: '/(auth)/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthLayoutSignInRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout': {
      id: '/(protected)/dashboard/_dashboard-layout'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(public)/offline/': {
      id: '/(public)/offline/'
      path: '/offline'
      fullPath: '/offline/'
      preLoaderRoute: typeof publicOfflineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/offline/$id': {
      id: '/(public)/offline/$id'
      path: '/offline/$id'
      fullPath: '/offline/$id'
      preLoaderRoute: typeof publicOfflineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/profile/$id': {
      id: '/(public)/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof publicProfileIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutRouteRoute
    }
    '/(protected)/dashboard/collections/$id': {
      id: '/(protected)/dashboard/collections/$id'
      path: '/collections/$id'
      fullPath: '/dashboard/collections/$id'
      preLoaderRoute: typeof protectedDashboardCollectionsIdRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/new': {
      id: '/(protected)/dashboard/collections/new'
      path: '/collections/new'
      fullPath: '/dashboard/collections/new'
      preLoaderRoute: typeof protectedDashboardCollectionsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/settings/profile': {
      id: '/(protected)/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof protectedDashboardSettingsProfileRouteRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/snippets/$id': {
      id: '/(protected)/dashboard/snippets/$id'
      path: '/snippets/$id'
      fullPath: '/dashboard/snippets/$id'
      preLoaderRoute: typeof protectedDashboardSnippetsIdRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/requests': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryRequestsRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/collections/$id/': {
      id: '/(protected)/dashboard/collections/$id/'
      path: '/'
      fullPath: '/dashboard/collections/$id/'
      preLoaderRoute: typeof protectedDashboardCollectionsIdIndexRouteImport
      parentRoute: typeof protectedDashboardCollectionsIdRouteRoute
    }
    '/(protected)/dashboard/settings/appearance/': {
      id: '/(protected)/dashboard/settings/appearance/'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance/'
      preLoaderRoute: typeof protectedDashboardSettingsAppearanceIndexRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/settings/security/': {
      id: '/(protected)/dashboard/settings/security/'
      path: '/security'
      fullPath: '/dashboard/settings/security/'
      preLoaderRoute: typeof protectedDashboardSettingsSecurityIndexRouteImport
      parentRoute: typeof protectedDashboardSettingsRouteRoute
    }
    '/(protected)/dashboard/snippets/$id/': {
      id: '/(protected)/dashboard/snippets/$id/'
      path: '/'
      fullPath: '/dashboard/snippets/$id/'
      preLoaderRoute: typeof protectedDashboardSnippetsIdIndexRouteImport
      parentRoute: typeof protectedDashboardSnippetsIdRouteRoute
    }
    '/(protected)/dashboard/snippets/new/': {
      id: '/(protected)/dashboard/snippets/new/'
      path: '/snippets/new'
      fullPath: '/dashboard/snippets/new/'
      preLoaderRoute: typeof protectedDashboardSnippetsNewIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/collections/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/collections/'
      path: '/collections'
      fullPath: '/dashboard/collections/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryCollectionsIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/discover/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/discover/'
      path: '/discover'
      fullPath: '/dashboard/discover/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryDiscoverIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/friends/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/friends/'
      path: '/friends'
      fullPath: '/dashboard/friends/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryFriendsIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/snippets/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/snippets/'
      path: '/snippets'
      fullPath: '/dashboard/snippets/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundarySnippetsIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/collections/$id/edit/': {
      id: '/(protected)/dashboard/collections/$id/edit/'
      path: '/edit'
      fullPath: '/dashboard/collections/$id/edit/'
      preLoaderRoute: typeof protectedDashboardCollectionsIdEditIndexRouteImport
      parentRoute: typeof protectedDashboardCollectionsIdRouteRoute
    }
    '/(protected)/dashboard/snippets/$id/edit/': {
      id: '/(protected)/dashboard/snippets/$id/edit/'
      path: '/edit'
      fullPath: '/dashboard/snippets/$id/edit/'
      preLoaderRoute: typeof protectedDashboardSnippetsIdEditIndexRouteImport
      parentRoute: typeof protectedDashboardSnippetsIdRouteRoute
    }
  }
}

interface authAuthLayoutRouteRouteChildren {
  authAuthLayoutAccountVerificationRoute: typeof authAuthLayoutAccountVerificationRoute
  authAuthLayoutForgotPasswordRoute: typeof authAuthLayoutForgotPasswordRoute
  authAuthLayoutPasswordResetRoute: typeof authAuthLayoutPasswordResetRoute
  authAuthLayoutRegisterAccountRoute: typeof authAuthLayoutRegisterAccountRoute
  authAuthLayoutSignInRoute: typeof authAuthLayoutSignInRoute
}

const authAuthLayoutRouteRouteChildren: authAuthLayoutRouteRouteChildren = {
  authAuthLayoutAccountVerificationRoute:
    authAuthLayoutAccountVerificationRoute,
  authAuthLayoutForgotPasswordRoute: authAuthLayoutForgotPasswordRoute,
  authAuthLayoutPasswordResetRoute: authAuthLayoutPasswordResetRoute,
  authAuthLayoutRegisterAccountRoute: authAuthLayoutRegisterAccountRoute,
  authAuthLayoutSignInRoute: authAuthLayoutSignInRoute,
}

const authAuthLayoutRouteRouteWithChildren =
  authAuthLayoutRouteRoute._addFileChildren(authAuthLayoutRouteRouteChildren)

interface protectedDashboardDashboardLayoutBoundaryRouteRouteChildren {
  protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute: typeof protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute
  protectedDashboardDashboardLayoutBoundaryIndexRoute: typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute: typeof protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute
  protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute: typeof protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute
  protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute: typeof protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute
  protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute: typeof protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute
}

const protectedDashboardDashboardLayoutBoundaryRouteRouteChildren: protectedDashboardDashboardLayoutBoundaryRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute:
      protectedDashboardDashboardLayoutBoundaryRequestsRouteRoute,
    protectedDashboardDashboardLayoutBoundaryIndexRoute:
      protectedDashboardDashboardLayoutBoundaryIndexRoute,
    protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute:
      protectedDashboardDashboardLayoutBoundaryCollectionsIndexRoute,
    protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute:
      protectedDashboardDashboardLayoutBoundaryDiscoverIndexRoute,
    protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute:
      protectedDashboardDashboardLayoutBoundaryFriendsIndexRoute,
    protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute:
      protectedDashboardDashboardLayoutBoundarySnippetsIndexRoute,
  }

const protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren =
  protectedDashboardDashboardLayoutBoundaryRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutBoundaryRouteRouteChildren,
  )

interface protectedDashboardDashboardLayoutRouteRouteChildren {
  protectedDashboardDashboardLayoutBoundaryRouteRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren
}

const protectedDashboardDashboardLayoutRouteRouteChildren: protectedDashboardDashboardLayoutRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutBoundaryRouteRoute:
      protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren,
  }

const protectedDashboardDashboardLayoutRouteRouteWithChildren =
  protectedDashboardDashboardLayoutRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutRouteRouteChildren,
  )

interface protectedDashboardSettingsRouteRouteChildren {
  protectedDashboardSettingsProfileRouteRoute: typeof protectedDashboardSettingsProfileRouteRoute
  protectedDashboardSettingsAppearanceIndexRoute: typeof protectedDashboardSettingsAppearanceIndexRoute
  protectedDashboardSettingsSecurityIndexRoute: typeof protectedDashboardSettingsSecurityIndexRoute
}

const protectedDashboardSettingsRouteRouteChildren: protectedDashboardSettingsRouteRouteChildren =
  {
    protectedDashboardSettingsProfileRouteRoute:
      protectedDashboardSettingsProfileRouteRoute,
    protectedDashboardSettingsAppearanceIndexRoute:
      protectedDashboardSettingsAppearanceIndexRoute,
    protectedDashboardSettingsSecurityIndexRoute:
      protectedDashboardSettingsSecurityIndexRoute,
  }

const protectedDashboardSettingsRouteRouteWithChildren =
  protectedDashboardSettingsRouteRoute._addFileChildren(
    protectedDashboardSettingsRouteRouteChildren,
  )

interface protectedDashboardCollectionsIdRouteRouteChildren {
  protectedDashboardCollectionsIdIndexRoute: typeof protectedDashboardCollectionsIdIndexRoute
  protectedDashboardCollectionsIdEditIndexRoute: typeof protectedDashboardCollectionsIdEditIndexRoute
}

const protectedDashboardCollectionsIdRouteRouteChildren: protectedDashboardCollectionsIdRouteRouteChildren =
  {
    protectedDashboardCollectionsIdIndexRoute:
      protectedDashboardCollectionsIdIndexRoute,
    protectedDashboardCollectionsIdEditIndexRoute:
      protectedDashboardCollectionsIdEditIndexRoute,
  }

const protectedDashboardCollectionsIdRouteRouteWithChildren =
  protectedDashboardCollectionsIdRouteRoute._addFileChildren(
    protectedDashboardCollectionsIdRouteRouteChildren,
  )

interface protectedDashboardSnippetsIdRouteRouteChildren {
  protectedDashboardSnippetsIdIndexRoute: typeof protectedDashboardSnippetsIdIndexRoute
  protectedDashboardSnippetsIdEditIndexRoute: typeof protectedDashboardSnippetsIdEditIndexRoute
}

const protectedDashboardSnippetsIdRouteRouteChildren: protectedDashboardSnippetsIdRouteRouteChildren =
  {
    protectedDashboardSnippetsIdIndexRoute:
      protectedDashboardSnippetsIdIndexRoute,
    protectedDashboardSnippetsIdEditIndexRoute:
      protectedDashboardSnippetsIdEditIndexRoute,
  }

const protectedDashboardSnippetsIdRouteRouteWithChildren =
  protectedDashboardSnippetsIdRouteRoute._addFileChildren(
    protectedDashboardSnippetsIdRouteRouteChildren,
  )

interface protectedDashboardRouteRouteChildren {
  protectedDashboardDashboardLayoutRouteRoute: typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  protectedDashboardSettingsRouteRoute: typeof protectedDashboardSettingsRouteRouteWithChildren
  protectedDashboardCollectionsIdRouteRoute: typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  protectedDashboardCollectionsNewRouteRoute: typeof protectedDashboardCollectionsNewRouteRoute
  protectedDashboardSnippetsIdRouteRoute: typeof protectedDashboardSnippetsIdRouteRouteWithChildren
  protectedDashboardSnippetsNewIndexRoute: typeof protectedDashboardSnippetsNewIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutRouteRoute:
      protectedDashboardDashboardLayoutRouteRouteWithChildren,
    protectedDashboardSettingsRouteRoute:
      protectedDashboardSettingsRouteRouteWithChildren,
    protectedDashboardCollectionsIdRouteRoute:
      protectedDashboardCollectionsIdRouteRouteWithChildren,
    protectedDashboardCollectionsNewRouteRoute:
      protectedDashboardCollectionsNewRouteRoute,
    protectedDashboardSnippetsIdRouteRoute:
      protectedDashboardSnippetsIdRouteRouteWithChildren,
    protectedDashboardSnippetsNewIndexRoute:
      protectedDashboardSnippetsNewIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authAuthLayoutRouteRoute: authAuthLayoutRouteRouteWithChildren,
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  publicGoodbyeRoute: publicGoodbyeRoute,
  publicIndexRoute: publicIndexRoute,
  publicProfileIdRouteRoute: publicProfileIdRouteRoute,
  publicOfflineIdRoute: publicOfflineIdRoute,
  publicOfflineIndexRoute: publicOfflineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
