/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authAuthLayoutRouteRouteImport } from './routes/(auth)/_auth-layout/route'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicGoodbyeRouteImport } from './routes/(public)/goodbye'
import { Route as authAuthLayoutAccountVerificationRouteImport } from './routes/(auth)/_auth-layout/account-verification'
import { Route as authAuthLayoutForgotPasswordRouteImport } from './routes/(auth)/_auth-layout/forgot-password'
import { Route as authAuthLayoutPasswordResetRouteImport } from './routes/(auth)/_auth-layout/password-reset'
import { Route as authAuthLayoutRegisterAccountRouteImport } from './routes/(auth)/_auth-layout/register-account'
import { Route as authAuthLayoutSignInRouteImport } from './routes/(auth)/_auth-layout/sign-in'
import { Route as protectedDashboardDashboardLayoutRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/route'
import { Route as publicOfflineIndexRouteImport } from './routes/(public)/offline/index'
import { Route as publicOfflineIdRouteImport } from './routes/(public)/offline/$id'
import { Route as publicProfileIdRouteRouteImport } from './routes/(public)/profile/$id/route'
import { Route as protectedDashboardDashboardLayoutBoundaryRouteRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/route'
import { Route as protectedDashboardCollectionsIdRouteRouteImport } from './routes/(protected)/dashboard/collections/$id/route'
import { Route as protectedDashboardCollectionsNewRouteRouteImport } from './routes/(protected)/dashboard/collections/new/route'
import { Route as protectedDashboardDashboardLayoutBoundaryIndexRouteImport } from './routes/(protected)/dashboard/_dashboard-layout/_boundary/index'
import { Route as protectedDashboardCollectionsIdIndexRouteImport } from './routes/(protected)/dashboard/collections/$id/index'
import { Route as protectedDashboardCollectionsIdEditRouteRouteImport } from './routes/(protected)/dashboard/collections/$id/edit/route'

const authAuthLayoutRouteRoute = authAuthLayoutRouteRouteImport.update({
  id: '/(auth)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGoodbyeRoute = publicGoodbyeRouteImport.update({
  id: '/(public)/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutAccountVerificationRoute =
  authAuthLayoutAccountVerificationRouteImport.update({
    id: '/account-verification',
    path: '/account-verification',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutForgotPasswordRoute =
  authAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutPasswordResetRoute =
  authAuthLayoutPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutRegisterAccountRoute =
  authAuthLayoutRegisterAccountRouteImport.update({
    id: '/register-account',
    path: '/register-account',
    getParentRoute: () => authAuthLayoutRouteRoute,
  } as any)
const authAuthLayoutSignInRoute = authAuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)
const protectedDashboardDashboardLayoutRouteRoute =
  protectedDashboardDashboardLayoutRouteRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const publicOfflineIndexRoute = publicOfflineIndexRouteImport.update({
  id: '/(public)/offline/',
  path: '/offline/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOfflineIdRoute = publicOfflineIdRouteImport.update({
  id: '/(public)/offline/$id',
  path: '/offline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProfileIdRouteRoute = publicProfileIdRouteRouteImport.update({
  id: '/(public)/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardDashboardLayoutBoundaryRouteRoute =
  protectedDashboardDashboardLayoutBoundaryRouteRouteImport.update({
    id: '/_boundary',
    getParentRoute: () => protectedDashboardDashboardLayoutRouteRoute,
  } as any)
const protectedDashboardCollectionsIdRouteRoute =
  protectedDashboardCollectionsIdRouteRouteImport.update({
    id: '/collections/$id',
    path: '/collections/$id',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCollectionsNewRouteRoute =
  protectedDashboardCollectionsNewRouteRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDashboardLayoutBoundaryIndexRoute =
  protectedDashboardDashboardLayoutBoundaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardDashboardLayoutBoundaryRouteRoute,
  } as any)
const protectedDashboardCollectionsIdIndexRoute =
  protectedDashboardCollectionsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardCollectionsIdRouteRoute,
  } as any)
const protectedDashboardCollectionsIdEditRouteRoute =
  protectedDashboardCollectionsIdEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => protectedDashboardCollectionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/goodbye': typeof publicGoodbyeRoute
  '/': typeof publicIndexRoute
  '/profile/$id': typeof publicProfileIdRouteRoute
  '/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/offline/$id': typeof publicOfflineIdRoute
  '/offline/': typeof publicOfflineIndexRoute
  '/dashboard/collections/$id': typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/collections/$id/edit': typeof protectedDashboardCollectionsIdEditRouteRoute
  '/dashboard/': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/dashboard/collections/$id/': typeof protectedDashboardCollectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/': typeof publicIndexRoute
  '/profile/$id': typeof publicProfileIdRouteRoute
  '/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/offline/$id': typeof publicOfflineIdRoute
  '/offline': typeof publicOfflineIndexRoute
  '/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/dashboard/collections/$id/edit': typeof protectedDashboardCollectionsIdEditRouteRoute
  '/dashboard/collections/$id': typeof protectedDashboardCollectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(public)/goodbye': typeof publicGoodbyeRoute
  '/(public)/': typeof publicIndexRoute
  '/(protected)/dashboard/_dashboard-layout': typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  '/(public)/profile/$id': typeof publicProfileIdRouteRoute
  '/(auth)/_auth-layout/account-verification': typeof authAuthLayoutAccountVerificationRoute
  '/(auth)/_auth-layout/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/(auth)/_auth-layout/password-reset': typeof authAuthLayoutPasswordResetRoute
  '/(auth)/_auth-layout/register-account': typeof authAuthLayoutRegisterAccountRoute
  '/(auth)/_auth-layout/sign-in': typeof authAuthLayoutSignInRoute
  '/(public)/offline/$id': typeof publicOfflineIdRoute
  '/(public)/offline/': typeof publicOfflineIndexRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary': typeof protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren
  '/(protected)/dashboard/collections/$id': typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  '/(protected)/dashboard/collections/new': typeof protectedDashboardCollectionsNewRouteRoute
  '/(protected)/dashboard/collections/$id/edit': typeof protectedDashboardCollectionsIdEditRouteRoute
  '/(protected)/dashboard/_dashboard-layout/_boundary/': typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
  '/(protected)/dashboard/collections/$id/': typeof protectedDashboardCollectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/goodbye'
    | '/'
    | '/profile/$id'
    | '/account-verification'
    | '/forgot-password'
    | '/password-reset'
    | '/register-account'
    | '/sign-in'
    | '/offline/$id'
    | '/offline/'
    | '/dashboard/collections/$id'
    | '/dashboard/collections/new'
    | '/dashboard/collections/$id/edit'
    | '/dashboard/'
    | '/dashboard/collections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/goodbye'
    | '/'
    | '/profile/$id'
    | '/account-verification'
    | '/forgot-password'
    | '/password-reset'
    | '/register-account'
    | '/sign-in'
    | '/offline/$id'
    | '/offline'
    | '/dashboard/collections/new'
    | '/dashboard/collections/$id/edit'
    | '/dashboard/collections/$id'
  id:
    | '__root__'
    | '/(auth)/_auth-layout'
    | '/(protected)/dashboard'
    | '/(public)/goodbye'
    | '/(public)/'
    | '/(protected)/dashboard/_dashboard-layout'
    | '/(public)/profile/$id'
    | '/(auth)/_auth-layout/account-verification'
    | '/(auth)/_auth-layout/forgot-password'
    | '/(auth)/_auth-layout/password-reset'
    | '/(auth)/_auth-layout/register-account'
    | '/(auth)/_auth-layout/sign-in'
    | '/(public)/offline/$id'
    | '/(public)/offline/'
    | '/(protected)/dashboard/_dashboard-layout/_boundary'
    | '/(protected)/dashboard/collections/$id'
    | '/(protected)/dashboard/collections/new'
    | '/(protected)/dashboard/collections/$id/edit'
    | '/(protected)/dashboard/_dashboard-layout/_boundary/'
    | '/(protected)/dashboard/collections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthLayoutRouteRoute: typeof authAuthLayoutRouteRouteWithChildren
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  publicGoodbyeRoute: typeof publicGoodbyeRoute
  publicIndexRoute: typeof publicIndexRoute
  publicProfileIdRouteRoute: typeof publicProfileIdRouteRoute
  publicOfflineIdRoute: typeof publicOfflineIdRoute
  publicOfflineIndexRoute: typeof publicOfflineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/goodbye': {
      id: '/(public)/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof publicGoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout/account-verification': {
      id: '/(auth)/_auth-layout/account-verification'
      path: '/account-verification'
      fullPath: '/account-verification'
      preLoaderRoute: typeof authAuthLayoutAccountVerificationRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/forgot-password': {
      id: '/(auth)/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/password-reset': {
      id: '/(auth)/_auth-layout/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authAuthLayoutPasswordResetRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/register-account': {
      id: '/(auth)/_auth-layout/register-account'
      path: '/register-account'
      fullPath: '/register-account'
      preLoaderRoute: typeof authAuthLayoutRegisterAccountRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/sign-in': {
      id: '/(auth)/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthLayoutSignInRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout': {
      id: '/(protected)/dashboard/_dashboard-layout'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(public)/offline/': {
      id: '/(public)/offline/'
      path: '/offline'
      fullPath: '/offline/'
      preLoaderRoute: typeof publicOfflineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/offline/$id': {
      id: '/(public)/offline/$id'
      path: '/offline/$id'
      fullPath: '/offline/$id'
      preLoaderRoute: typeof publicOfflineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/profile/$id': {
      id: '/(public)/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof publicProfileIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutRouteRoute
    }
    '/(protected)/dashboard/collections/$id': {
      id: '/(protected)/dashboard/collections/$id'
      path: '/collections/$id'
      fullPath: '/dashboard/collections/$id'
      preLoaderRoute: typeof protectedDashboardCollectionsIdRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/collections/new': {
      id: '/(protected)/dashboard/collections/new'
      path: '/collections/new'
      fullPath: '/dashboard/collections/new'
      preLoaderRoute: typeof protectedDashboardCollectionsNewRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/_dashboard-layout/_boundary/': {
      id: '/(protected)/dashboard/_dashboard-layout/_boundary/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardDashboardLayoutBoundaryIndexRouteImport
      parentRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRoute
    }
    '/(protected)/dashboard/collections/$id/': {
      id: '/(protected)/dashboard/collections/$id/'
      path: '/'
      fullPath: '/dashboard/collections/$id/'
      preLoaderRoute: typeof protectedDashboardCollectionsIdIndexRouteImport
      parentRoute: typeof protectedDashboardCollectionsIdRouteRoute
    }
    '/(protected)/dashboard/collections/$id/edit': {
      id: '/(protected)/dashboard/collections/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/collections/$id/edit'
      preLoaderRoute: typeof protectedDashboardCollectionsIdEditRouteRouteImport
      parentRoute: typeof protectedDashboardCollectionsIdRouteRoute
    }
  }
}

interface authAuthLayoutRouteRouteChildren {
  authAuthLayoutAccountVerificationRoute: typeof authAuthLayoutAccountVerificationRoute
  authAuthLayoutForgotPasswordRoute: typeof authAuthLayoutForgotPasswordRoute
  authAuthLayoutPasswordResetRoute: typeof authAuthLayoutPasswordResetRoute
  authAuthLayoutRegisterAccountRoute: typeof authAuthLayoutRegisterAccountRoute
  authAuthLayoutSignInRoute: typeof authAuthLayoutSignInRoute
}

const authAuthLayoutRouteRouteChildren: authAuthLayoutRouteRouteChildren = {
  authAuthLayoutAccountVerificationRoute:
    authAuthLayoutAccountVerificationRoute,
  authAuthLayoutForgotPasswordRoute: authAuthLayoutForgotPasswordRoute,
  authAuthLayoutPasswordResetRoute: authAuthLayoutPasswordResetRoute,
  authAuthLayoutRegisterAccountRoute: authAuthLayoutRegisterAccountRoute,
  authAuthLayoutSignInRoute: authAuthLayoutSignInRoute,
}

const authAuthLayoutRouteRouteWithChildren =
  authAuthLayoutRouteRoute._addFileChildren(authAuthLayoutRouteRouteChildren)

interface protectedDashboardDashboardLayoutBoundaryRouteRouteChildren {
  protectedDashboardDashboardLayoutBoundaryIndexRoute: typeof protectedDashboardDashboardLayoutBoundaryIndexRoute
}

const protectedDashboardDashboardLayoutBoundaryRouteRouteChildren: protectedDashboardDashboardLayoutBoundaryRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutBoundaryIndexRoute:
      protectedDashboardDashboardLayoutBoundaryIndexRoute,
  }

const protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren =
  protectedDashboardDashboardLayoutBoundaryRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutBoundaryRouteRouteChildren,
  )

interface protectedDashboardDashboardLayoutRouteRouteChildren {
  protectedDashboardDashboardLayoutBoundaryRouteRoute: typeof protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren
}

const protectedDashboardDashboardLayoutRouteRouteChildren: protectedDashboardDashboardLayoutRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutBoundaryRouteRoute:
      protectedDashboardDashboardLayoutBoundaryRouteRouteWithChildren,
  }

const protectedDashboardDashboardLayoutRouteRouteWithChildren =
  protectedDashboardDashboardLayoutRouteRoute._addFileChildren(
    protectedDashboardDashboardLayoutRouteRouteChildren,
  )

interface protectedDashboardCollectionsIdRouteRouteChildren {
  protectedDashboardCollectionsIdEditRouteRoute: typeof protectedDashboardCollectionsIdEditRouteRoute
  protectedDashboardCollectionsIdIndexRoute: typeof protectedDashboardCollectionsIdIndexRoute
}

const protectedDashboardCollectionsIdRouteRouteChildren: protectedDashboardCollectionsIdRouteRouteChildren =
  {
    protectedDashboardCollectionsIdEditRouteRoute:
      protectedDashboardCollectionsIdEditRouteRoute,
    protectedDashboardCollectionsIdIndexRoute:
      protectedDashboardCollectionsIdIndexRoute,
  }

const protectedDashboardCollectionsIdRouteRouteWithChildren =
  protectedDashboardCollectionsIdRouteRoute._addFileChildren(
    protectedDashboardCollectionsIdRouteRouteChildren,
  )

interface protectedDashboardRouteRouteChildren {
  protectedDashboardDashboardLayoutRouteRoute: typeof protectedDashboardDashboardLayoutRouteRouteWithChildren
  protectedDashboardCollectionsIdRouteRoute: typeof protectedDashboardCollectionsIdRouteRouteWithChildren
  protectedDashboardCollectionsNewRouteRoute: typeof protectedDashboardCollectionsNewRouteRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardDashboardLayoutRouteRoute:
      protectedDashboardDashboardLayoutRouteRouteWithChildren,
    protectedDashboardCollectionsIdRouteRoute:
      protectedDashboardCollectionsIdRouteRouteWithChildren,
    protectedDashboardCollectionsNewRouteRoute:
      protectedDashboardCollectionsNewRouteRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authAuthLayoutRouteRoute: authAuthLayoutRouteRouteWithChildren,
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  publicGoodbyeRoute: publicGoodbyeRoute,
  publicIndexRoute: publicIndexRoute,
  publicProfileIdRouteRoute: publicProfileIdRouteRoute,
  publicOfflineIdRoute: publicOfflineIdRoute,
  publicOfflineIndexRoute: publicOfflineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
