import { z } from "../zod";
export declare const GetUserRequestDto: z.ZodObject<{
    name: z.ZodString;
}, z.core.$strip>;
export type GetUserRequestDtoType = z.infer<typeof GetUserRequestDto>;
export declare const GetUserSuccessResponseDto: z.ZodObject<{
    status: z.ZodNumber;
    message: z.ZodString;
    type: z.ZodLiteral<"success">;
    data: z.ZodObject<{
        profile: z.ZodObject<{
            name: z.ZodString;
            createdAt: z.ZodDate;
            updatedAt: z.ZodDate;
            firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            email: z.ZodEmail;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            isPrivate: z.ZodDefault<z.ZodBoolean>;
            emailVerifiedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
        }, z.core.$strip>;
        stats: z.ZodObject<{
            snippetsCount: z.ZodNumber;
            collectionsCount: z.ZodNumber;
            forkedSnippetsCount: z.ZodNumber;
            forkedCollectionsCount: z.ZodNumber;
            friendsCount: z.ZodNumber;
            friendsInboxCount: z.ZodNumber;
            friendsOutboxCount: z.ZodNumber;
        }, z.core.$strip>;
        type: z.ZodLiteral<"owner-success">;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const GetPublicUserSuccessResponseDto: z.ZodObject<{
    status: z.ZodNumber;
    message: z.ZodString;
    type: z.ZodLiteral<"success">;
    data: z.ZodObject<{
        stats: z.ZodObject<{
            snippetsCount: z.ZodNumber;
            collectionsCount: z.ZodNumber;
            forkedSnippetsCount: z.ZodNumber;
            forkedCollectionsCount: z.ZodNumber;
            friendsCount: z.ZodNumber;
            friendsInboxCount: z.ZodNumber;
            friendsOutboxCount: z.ZodNumber;
        }, z.core.$strip>;
        friendshipInfo: z.ZodObject<{
            isCurrentUserAFriend: z.ZodBoolean;
            requestStatus: any;
        }, z.core.$strip>;
        profile: z.ZodObject<{
            name: z.ZodString;
            createdAt: z.ZodDate;
            firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            email: z.ZodEmail;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>;
        type: z.ZodLiteral<"public-success">;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const GetUserResponseDto: z.ZodDiscriminatedUnion<[z.ZodObject<{
    status: z.ZodNumber;
    message: z.ZodString;
    type: z.ZodLiteral<"success">;
    data: z.ZodObject<{
        profile: z.ZodObject<{
            name: z.ZodString;
            createdAt: z.ZodDate;
            updatedAt: z.ZodDate;
            firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            email: z.ZodEmail;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            isPrivate: z.ZodDefault<z.ZodBoolean>;
            emailVerifiedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
        }, z.core.$strip>;
        stats: z.ZodObject<{
            snippetsCount: z.ZodNumber;
            collectionsCount: z.ZodNumber;
            forkedSnippetsCount: z.ZodNumber;
            forkedCollectionsCount: z.ZodNumber;
            friendsCount: z.ZodNumber;
            friendsInboxCount: z.ZodNumber;
            friendsOutboxCount: z.ZodNumber;
        }, z.core.$strip>;
        type: z.ZodLiteral<"owner-success">;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    status: z.ZodNumber;
    message: z.ZodString;
    type: z.ZodLiteral<"success">;
    data: z.ZodObject<{
        stats: z.ZodObject<{
            snippetsCount: z.ZodNumber;
            collectionsCount: z.ZodNumber;
            forkedSnippetsCount: z.ZodNumber;
            forkedCollectionsCount: z.ZodNumber;
            friendsCount: z.ZodNumber;
            friendsInboxCount: z.ZodNumber;
            friendsOutboxCount: z.ZodNumber;
        }, z.core.$strip>;
        friendshipInfo: z.ZodObject<{
            isCurrentUserAFriend: z.ZodBoolean;
            requestStatus: any;
        }, z.core.$strip>;
        profile: z.ZodObject<{
            name: z.ZodString;
            createdAt: z.ZodDate;
            firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            email: z.ZodEmail;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>;
        type: z.ZodLiteral<"public-success">;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    type: z.ZodLiteral<"error">;
    status: z.ZodNumber;
    message: z.ZodString;
    cause: z.ZodNullable<z.ZodString>;
}, z.core.$strip>], "type">;
export type GetUserResponseDtoType = z.infer<typeof GetUserResponseDto>;
export declare const GetCurrentUserResponseDto: z.ZodDiscriminatedUnion<[z.ZodObject<{
    status: z.ZodNumber;
    message: z.ZodString;
    type: z.ZodLiteral<"success">;
    data: z.ZodObject<{
        profile: z.ZodObject<{
            name: z.ZodString;
            createdAt: z.ZodDate;
            updatedAt: z.ZodDate;
            firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            email: z.ZodEmail;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            isPrivate: z.ZodDefault<z.ZodBoolean>;
            emailVerifiedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
        }, z.core.$strip>;
        stats: z.ZodObject<{
            snippetsCount: z.ZodNumber;
            collectionsCount: z.ZodNumber;
            forkedSnippetsCount: z.ZodNumber;
            forkedCollectionsCount: z.ZodNumber;
            friendsCount: z.ZodNumber;
            friendsInboxCount: z.ZodNumber;
            friendsOutboxCount: z.ZodNumber;
        }, z.core.$strip>;
        type: z.ZodLiteral<"owner-success">;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    type: z.ZodLiteral<"error">;
    status: z.ZodNumber;
    message: z.ZodString;
    cause: z.ZodNullable<z.ZodString>;
}, z.core.$strip>], "type">;
export type GetCurrentUserResponseDtoType = z.infer<typeof GetCurrentUserResponseDto>;
