import { z } from "../zod";
export declare const SelectUserDto: z.ZodObject<{
    id: z.ZodNumber;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    name: z.ZodString;
    oldNames: z.ZodDefault<z.ZodArray<z.ZodString>>;
    firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    email: z.ZodEmail;
    password: z.ZodString;
    bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    image: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    imageCustomId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    imageKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    rememberMe: z.ZodDefault<z.ZodBoolean>;
    isPrivate: z.ZodDefault<z.ZodBoolean>;
    acceptedPolicies: z.ZodDefault<z.ZodBoolean>;
    emailVerifiedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    emailVerificationToken: z.ZodOptional<z.ZodNullable<z.ZodUUID>>;
    emailVerificationTokenExpiresAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    resetPasswordToken: z.ZodOptional<z.ZodNullable<z.ZodUUID>>;
    resetPasswordTokenExpiresAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    refreshTokens: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type SelectUserDtoType = z.infer<typeof SelectUserDto>;
