/* eslint-disable */
/**
 * ---------------------------------------------------------
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
 * ---------------------------------------------------------
 */

export const LanguageCodes = {
  "Afrikaans": "af",
  "Akan": "ak",
  "Albanian": "sq",
  "Amharic": "am",
  "Arabic": "ar",
  "Armenian": "hy",
  "Assamese": "as",
  "Azerbaijani": "az",
  "Bambara": "bm",
  "Bangla": "bn",
  "Basque": "eu",
  "Belarusian": "be",
  "Bosnian": "bs",
  "Breton": "br",
  "Bulgarian": "bg",
  "Burmese": "my",
  "Catalan": "ca",
  "Chechen": "ce",
  "Chinese": "zh",
  "SimplifiedChinese": "zh_Hans",
  "TraditionalChinese": "zh_Hant",
  "English": "en",
  "AustralianEnglish": "en_AU",
  "CanadianEnglish": "en_CA",
  "BritishEnglish": "en_GB",
  "AmericanEnglish": "en_US",
  "French": "fr",
  "CanadianFrench": "fr_CA",
  "SwissFrench": "fr_CH",
  "German": "de",
  "AustrianGerman": "de_AT",
  "SwissHighGerman": "de_CH",
  "Spanish": "es",
  "EuropeanSpanish": "es_ES",
  "MexicanSpanish": "es_MX",
  "Portuguese": "pt",
  "BrazilianPortuguese": "pt_BR",
  "EuropeanPortuguese": "pt_PT",
  "Italian": "it",
  "Japanese": "ja",
  "Korean": "ko",
  "Russian": "ru",
  "Turkish": "tr",
  "Ukrainian": "uk",
  "Vietnamese": "vi",
  "ArabicSaudi": "ar_SA",
  "Zulu": "zu"
} as const;

export enum LanguageCode {
  Afrikaans = "af",
  Akan = "ak",
  Albanian = "sq",
  Amharic = "am",
  Arabic = "ar",
  Armenian = "hy",
  Assamese = "as",
  Azerbaijani = "az",
  Bambara = "bm",
  Bangla = "bn",
  Basque = "eu",
  Belarusian = "be",
  Bosnian = "bs",
  Breton = "br",
  Bulgarian = "bg",
  Burmese = "my",
  Catalan = "ca",
  Chechen = "ce",
  Chinese = "zh",
  SimplifiedChinese = "zh_Hans",
  TraditionalChinese = "zh_Hant",
  English = "en",
  AustralianEnglish = "en_AU",
  CanadianEnglish = "en_CA",
  BritishEnglish = "en_GB",
  AmericanEnglish = "en_US",
  French = "fr",
  CanadianFrench = "fr_CA",
  SwissFrench = "fr_CH",
  German = "de",
  AustrianGerman = "de_AT",
  SwissHighGerman = "de_CH",
  Spanish = "es",
  EuropeanSpanish = "es_ES",
  MexicanSpanish = "es_MX",
  Portuguese = "pt",
  BrazilianPortuguese = "pt_BR",
  EuropeanPortuguese = "pt_PT",
  Italian = "it",
  Japanese = "ja",
  Korean = "ko",
  Russian = "ru",
  Turkish = "tr",
  Ukrainian = "uk",
  Vietnamese = "vi",
  ArabicSaudi = "ar_SA",
  Zulu = "zu",
}

export type LanguageCodesUnion = "af" | "ak" | "sq" | "am" | "ar" | "hy" | "as" | "az" | "bm" | "bn" | "eu" | "be" | "bs" | "br" | "bg" | "my" | "ca" | "ce" | "zh" | "zh_Hans" | "zh_Hant" | "en" | "en_AU" | "en_CA" | "en_GB" | "en_US" | "fr" | "fr_CA" | "fr_CH" | "de" | "de_AT" | "de_CH" | "es" | "es_ES" | "es_MX" | "pt" | "pt_BR" | "pt_PT" | "it" | "ja" | "ko" | "ru" | "tr" | "uk" | "vi" | "ar_SA" | "zu";

